version: "3"
services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    tty: true
    command: start --log debug --user root --pass root